version: '3.8'

services:
  gazprom.api:
    image: gazprom.api
    build:
      context: .
      dockerfile: Gazprom.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=database
      - DB_USER=SA
      - DB_PASSWORD=YourStrong!Passw0rd
      - DB_NAME=GazpromDB
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1432:1433"
    volumes:
      - sql_data:/var/opt/mssql
        
  frontend:
    build:
      context: ./client  # Путь к папке с React-проектом
      dockerfile: Dockerfile        # Dockerfile для React
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://gazprom.api:8080  # URL API для фронтенда
    depends_on:
      - gazprom.api
    volumes:
      - ./client/src:/app/src           # Hot-reload для разработки
      - ./client/public:/app/public

volumes:
  sql_data:
