// <auto-generated />
using System;
using Gazprom.API.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gazprom.API.Infrastructure
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Domain.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mark = "Toyota",
                            Model = "Camry",
                            RegistrationDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 2,
                            Mark = "Toyota",
                            Model = "RAV4",
                            RegistrationDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 1
                        },
                        new
                        {
                            Id = 3,
                            Mark = "Samsung",
                            Model = "Galaxy S23",
                            RegistrationDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 2
                        },
                        new
                        {
                            Id = 4,
                            Mark = "Apple",
                            Model = "iPhone 14",
                            RegistrationDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 5,
                            Mark = "Apple",
                            Model = "MacBook Pro",
                            RegistrationDate = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 3
                        },
                        new
                        {
                            Id = 6,
                            Mark = "Microsoft",
                            Model = "Surface Pro 9",
                            RegistrationDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 4
                        },
                        new
                        {
                            Id = 7,
                            Mark = "Sony",
                            Model = "PlayStation 5",
                            RegistrationDate = new DateTime(2023, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 5
                        },
                        new
                        {
                            Id = 8,
                            Mark = "Sony",
                            Model = "WH-1000XM5",
                            RegistrationDate = new DateTime(2023, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SupplierId = 5
                        });
                });

            modelBuilder.Entity("WebApplication1.Domain.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Supplier");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1937, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1938, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1976, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1975, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(1946, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony"
                        });
                });

            modelBuilder.Entity("WebApplication1.Domain.Offer", b =>
                {
                    b.HasOne("WebApplication1.Domain.Supplier", "Supplier")
                        .WithMany("Offers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("WebApplication1.Domain.Supplier", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
